//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalDbEntities : DbContext
    {
        public FinalDbEntities()
            : base("name=FinalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<common> commons { get; set; }
        public virtual DbSet<condoctor> condoctors { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<Purchase_Product> Purchase_Product { get; set; }
        public virtual DbSet<Purchase_Table> Purchase_Table { get; set; }
        public virtual DbSet<test_Data> test_Data { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
