//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Purchase_Table
    {
        public int Purchase_Id { get; set; }
        public string Purchase_No { get; set; }
        public System.DateTime Date { get; set; }
        public int Total { get; set; }
        [NotMapped]
        public List <Purchase_Product> Purchase_Product { get; set; }
    }
}
